### ISSUE TITLE
Cursor based lexer

### ISSUE THREAD

**Issue by bluebrown** [hashicorp/mql#16]
**Is your feature request related to a problem? Please describe.**

I took a look at the lexer implementation, and it appears that there is room for performance improvement. 

**Describe the solution you'd like**

I would like to change the lexer implementation to keep track of a "cursor" instead of pushing/popping a stack.

**Describe alternatives you've considered**

Alternatively, the current lexer remains.

**Additional context**

**Comment by jimlambrt** [comment]
I think for now, we'll keep the lever as is. At some point, if there are real world performance concerns, we can reconsider this approach.
